// <auto-generated />
using System;
using ArcaneVault.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArcaneVault.Data.Migrations
{
    [DbContext(typeof(ArcaneVaultDbContext))]
    [Migration("20260816050634_LockRequestedItemsWhenTradeCreated")]
    partial class LockRequestedItemsWhenTradeCreated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ArcaneVault.Models.Entities.ArcaneVaultUser", b =>
                {
                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserName");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("ArcaneVaultUsers", (string)null);
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.ArcaneVaultUserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("ArcaneVaultUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "User"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Staff"
                        });
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.Category", b =>
                {
                    b.Property<string>("CategoryCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("CategoryCode");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.CollectionItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Good");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsInTrade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemTypeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("LockedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Common");

                    b.Property<int>("StartingQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("ItemId");

                    b.HasIndex("ItemTypeId");

                    b.HasIndex("UserName");

                    b.ToTable("CollectionItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_CollectionItems_Condition_Valid", "Condition IN ('Mint', 'Good', 'Fair', 'Poor')");

                            t.HasCheckConstraint("CK_CollectionItems_CurrentQuantity_NonNegative", "CurrentQuantity >= 0");

                            t.HasCheckConstraint("CK_CollectionItems_LockedQuantity_Valid", "LockedQuantity >= 0 AND LockedQuantity <= CurrentQuantity");

                            t.HasCheckConstraint("CK_CollectionItems_Rarity_Valid", "Rarity IN ('Common', 'Rare', 'Ultra Rare')");

                            t.HasCheckConstraint("CK_CollectionItems_StartingQuantity_NonNegative", "StartingQuantity >= 0");
                        });
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.CollectionItemCategory", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("ItemId", "CategoryCode");

                    b.HasIndex("CategoryCode");

                    b.ToTable("CollectionItemCategories", (string)null);
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.CollectionItemQuantityHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("HistoryId");

                    b.HasIndex("ItemId", "ChangedAtUtc");

                    b.ToTable("CollectionItemQuantityHistory", null, t =>
                        {
                            t.HasCheckConstraint("CK_CollectionItemQuantityHistory_Quantity_NonNegative", "Quantity >= 0");
                        });
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.ItemType", b =>
                {
                    b.Property<string>("ItemTypeId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("ItemTypeId");

                    b.HasIndex("ItemName");

                    b.ToTable("ItemTypes", (string)null);
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.Trade", b =>
                {
                    b.Property<int>("TradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisputeReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RecipientConfirmedComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecipientUserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<bool>("RequestedItemsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequesterConfirmedComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequesterUserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("ResolvedByStaffUserName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("StaffResolutionNote")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WishlistItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TradeId");

                    b.HasIndex("WishlistItemId");

                    b.HasIndex("RecipientUserName", "Status");

                    b.HasIndex("RequesterUserName", "Status");

                    b.ToTable("Trades", (string)null);
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.TradeItem", b =>
                {
                    b.Property<int>("TradeItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollectionItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TradeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TransferredCollectionItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TradeItemId");

                    b.HasIndex("CollectionItemId");

                    b.HasIndex("TransferredCollectionItemId");

                    b.HasIndex("TradeId", "CollectionItemId")
                        .IsUnique();

                    b.ToTable("TradeItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_TradeItems_Quantity_Positive", "Quantity > 0");
                        });
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.WishlistItem", b =>
                {
                    b.Property<int>("WishlistItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DesiredQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("WishlistItemId");

                    b.HasIndex("UserName");

                    b.ToTable("WishlistItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_WishlistItems_DesiredQuantity_Positive", "DesiredQuantity > 0");
                        });
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.ArcaneVaultUser", b =>
                {
                    b.HasOne("ArcaneVault.Models.Entities.ArcaneVaultUserRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.CollectionItem", b =>
                {
                    b.HasOne("ArcaneVault.Models.Entities.ItemType", "ItemType")
                        .WithMany("CollectionItems")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArcaneVault.Models.Entities.ArcaneVaultUser", "User")
                        .WithMany("CollectionItems")
                        .HasForeignKey("UserName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.CollectionItemCategory", b =>
                {
                    b.HasOne("ArcaneVault.Models.Entities.Category", "Category")
                        .WithMany("CollectionItemCategories")
                        .HasForeignKey("CategoryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArcaneVault.Models.Entities.CollectionItem", "CollectionItem")
                        .WithMany("CollectionItemCategories")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CollectionItem");
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.CollectionItemQuantityHistory", b =>
                {
                    b.HasOne("ArcaneVault.Models.Entities.CollectionItem", "CollectionItem")
                        .WithMany("QuantityHistory")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CollectionItem");
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.Trade", b =>
                {
                    b.HasOne("ArcaneVault.Models.Entities.WishlistItem", "WishlistItem")
                        .WithMany("Trades")
                        .HasForeignKey("WishlistItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("WishlistItem");
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.TradeItem", b =>
                {
                    b.HasOne("ArcaneVault.Models.Entities.CollectionItem", "CollectionItem")
                        .WithMany("TradeItems")
                        .HasForeignKey("CollectionItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArcaneVault.Models.Entities.Trade", "Trade")
                        .WithMany("TradeItems")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArcaneVault.Models.Entities.CollectionItem", "TransferredCollectionItem")
                        .WithMany("ReceivedTradeItems")
                        .HasForeignKey("TransferredCollectionItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CollectionItem");

                    b.Navigation("Trade");

                    b.Navigation("TransferredCollectionItem");
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.WishlistItem", b =>
                {
                    b.HasOne("ArcaneVault.Models.Entities.ArcaneVaultUser", "User")
                        .WithMany("WishlistItems")
                        .HasForeignKey("UserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.ArcaneVaultUser", b =>
                {
                    b.Navigation("CollectionItems");

                    b.Navigation("WishlistItems");
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.ArcaneVaultUserRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.Category", b =>
                {
                    b.Navigation("CollectionItemCategories");
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.CollectionItem", b =>
                {
                    b.Navigation("CollectionItemCategories");

                    b.Navigation("QuantityHistory");

                    b.Navigation("ReceivedTradeItems");

                    b.Navigation("TradeItems");
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.ItemType", b =>
                {
                    b.Navigation("CollectionItems");
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.Trade", b =>
                {
                    b.Navigation("TradeItems");
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.WishlistItem", b =>
                {
                    b.Navigation("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
