// Name:
// Student Admin No.:
// Tutorial Group:
// <auto-generated />
using ArcaneVault.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArcaneVault.Data.Migrations
{
    [DbContext(typeof(ArcaneVaultDbContext))]
    partial class ArcaneVaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ArcaneVault.Models.Entities.ArcaneVaultUser", b =>
                {
                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserName");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("ArcaneVaultUsers", (string)null);
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.ArcaneVaultUserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("ArcaneVaultUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "User"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Staff"
                        });
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.Category", b =>
                {
                    b.Property<string>("CategoryCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("CategoryCode");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.CollectionItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("StartingQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("ItemId");

                    b.HasIndex("UserName");

                    b.ToTable("CollectionItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_CollectionItems_CurrentQuantity_NonNegative", "CurrentQuantity >= 0");

                            t.HasCheckConstraint("CK_CollectionItems_StartingQuantity_NonNegative", "StartingQuantity >= 0");
                        });
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.CollectionItemCategory", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("ItemId", "CategoryCode");

                    b.HasIndex("CategoryCode");

                    b.ToTable("CollectionItemCategories", (string)null);
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.ArcaneVaultUser", b =>
                {
                    b.HasOne("ArcaneVault.Models.Entities.ArcaneVaultUserRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.CollectionItem", b =>
                {
                    b.HasOne("ArcaneVault.Models.Entities.ArcaneVaultUser", "User")
                        .WithMany("CollectionItems")
                        .HasForeignKey("UserName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.CollectionItemCategory", b =>
                {
                    b.HasOne("ArcaneVault.Models.Entities.Category", "Category")
                        .WithMany("CollectionItemCategories")
                        .HasForeignKey("CategoryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArcaneVault.Models.Entities.CollectionItem", "CollectionItem")
                        .WithMany("CollectionItemCategories")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CollectionItem");
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.ArcaneVaultUser", b =>
                {
                    b.Navigation("CollectionItems");
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.ArcaneVaultUserRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.Category", b =>
                {
                    b.Navigation("CollectionItemCategories");
                });

            modelBuilder.Entity("ArcaneVault.Models.Entities.CollectionItem", b =>
                {
                    b.Navigation("CollectionItemCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
